### ISSUE TITLE
error：No such file or directory: '/etc/sysctl.conf

### ISSUE THREAD

**Issue by ati46** [GitHackTools/TorghostNG#1]
$ sudo torghostng -s -m wlp0s20f3 
[+] Applying display language... Done
 _____               _               _   _   _  ____ 
|_   _|__  _ __ __ _| |__   ___  ___| |_| \ | |/ ___|
  | |/ _ \| '__/ _` | '_ \ / _ \/ __| __|  \| | |  _ 
  | | (_) | | | (_| | | | | (_) \__ \ |_| |\  | |_| |
  |_|\___/|_|  \__, |_| |_|\___/|___/\__|_| \_|\____|
               |___/
TorghostNG 1.3 - Make all your internet traffic anonymized through Tor proxy
Rewritten from TorGhost with Python 3

[+] Changing your current MAC address...
Current MAC:   28:7f:cf:63:da:0d (unknown)
Permanent MAC: 28:7f:cf:63:da:0d (unknown)
New MAC:       22:e8:2b:b3:8a:2d (unknown)
[*] You MAC address has been changed
[i] You can use 'ifconfig' to show interface devices
[+] Start connecting to Tor
Traceback (most recent call last):
  File "torghostng.py", line 474, in <module>
    start_connecting()
  File "torghostng.py", line 268, in start_connecting
    if DISABLE_IPv6 == open(Sysctl).read():
FileNotFoundError: [Errno 2] No such file or directory: '/etc/sysctl.conf'
[17507] Failed to execute script torghostng

**Comment by gitkern3l** [comment]
What GNU/Linux distro are you using?

**Comment by ati46** [comment]
archlinux + i3wm

发自我的iPhone

在 2020年5月7日，下午3:30，Git Kern3l <notifications@github.com> 写道：

﻿

What GNU/Linux distro are you using?

**Comment by gitkern3l** [comment]
Can you check "sysctl" command?

**Comment by gitkern3l** [comment]
Well, you can use `touch /etc/sysctl.conf` to create  `/etc/sysctl.conf` file

**Comment by gitkern3l** [comment]
Well you can give Torghost 1.7 a try. May be it can fix your problem (auto create `sysctl.conf`)
