### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by githubbers420** [GitHackTools/TorghostNG#6]
before its fine, but now always at "checking tor connection"
![Screenshot from 2020-06-06 12-16-46](https://user-images.githubusercontent.com/58240537/83949335-2b156200-a7f1-11ea-8a16-339da572bf1e.png)

**Comment by gitkern3l** [comment]
So what comman did you use to run TorghostNG?

**Comment by scorpiopd** [comment]
disconnect first from connection totally by running torghostng -x
and then reconnect it will work

> before its fine, but now always at "checking tor connection"
> ![Screenshot from 2020-06-06 12-16-46](https://user-images.githubusercontent.com/58240537/83949335-2b156200-a7f1-11ea-8a16-339da572bf1e.png)

**Comment by gitkern3l** [comment]
TorghostNG 1.6 has been released. Try it

**Comment by gitkern3l** [comment]
Have u install curl yet?

**Comment by gitkern3l** [comment]
Well you can give Torghost 1.7 a try
