### ISSUE TITLE
It fails if you don't have IPv6

### ISSUE THREAD

**Issue by DeadS3c** [GitHackTools/TorghostNG#7]
Hi, i just see that the script fails if you (for any reason), don't have IPv6:
![imagen](https://user-images.githubusercontent.com/52109756/85283653-03c7c180-b48e-11ea-9ab4-62c252b69875.png)

A quick workaround is to change the torghostng.py for checking if the file exists on the line 297:
![imagen](https://user-images.githubusercontent.com/52109756/85283767-31146f80-b48e-11ea-80c0-cae366e5ce26.png)

![imagen](https://user-images.githubusercontent.com/52109756/85283850-5bfec380-b48e-11ea-90c4-9f4ce9e5905b.png)

And now it works:
![imagen](https://user-images.githubusercontent.com/52109756/85283935-851f5400-b48e-11ea-9922-d9ed0399c38b.png)

Btw, amazing script, i love it!!

See ya

**Comment by gitkern3l** [comment]
Thank you!

**Comment by gitkern3l** [comment]
I'm going to fix your problem

**Comment by gitkern3l** [comment]
Take a look at TorghostNG 1.6 😃

**Comment by gitkern3l** [comment]
For your safe, TorghostNG auto turn off IPv6 while using Tor

**Comment by DeadS3c** [comment]
Hey, thank you for!! I'll check it later

**Comment by DeadS3c** [comment]
It seems to work rigth now, but it gets stucks on Checking Tor Connection...

![imagen](https://user-images.githubusercontent.com/52109756/94995294-b46d5300-059d-11eb-8c03-d45702c959f7.png)

**Comment by gitkern3l** [comment]
What distro u use?

**Comment by gitkern3l** [comment]
Have u install curl yet?

**Comment by gitkern3l** [comment]
Well you can give Torghost 1.7 a try

**Comment by gitkern3l** [comment]
Well you can give Torghost 1.7 a try. May be it can fix your problem

**Comment by gitkern3l** [comment]
That bug has been fixed in *TorghostNG 2.0*
Update to **TorghostNG 2.0** 😃
